using System;
using UnityEngine;
using EchoRealm.AI;

namespace EchoRealm.Characters
{
    /// <summary>
    /// Controls the Dobby character: animations, dialogue display, and emotional state.
    /// Dobby is the protagonist/guide — friendly, reactive, and expressive.
    ///
    /// Animations are triggered by CommandExecutor (via Animator triggers).
    /// Dialogue is generated by Ollama and displayed as floating text above Dobby.
    ///
    /// Setup:
    /// - Attach to Dobby's root GameObject (with Animator component)
    /// - Assign dialogueText (TextMeshPro) as a child positioned above Dobby's head
    /// - Animator must have triggers: Dance, Wave, Scared, Celebrate, Walk, Idle
    /// </summary>
    public class DobbyController : MonoBehaviour
    {
        [Header("References")]
        [SerializeField] private Animator animator;
        [SerializeField] private TMPro.TextMeshPro dialogueText;

        [Header("Dialogue Settings")]
        [Tooltip("How long dialogue text stays visible (seconds).")]
        [SerializeField] private float dialogueDisplayTime = 5f;

        [Tooltip("If true, dialogue text always faces the camera (billboard effect).")]
        [SerializeField] private bool billboardDialogue = true;

        [Header("Debug")]
        [SerializeField] private bool logEvents = true;

        /// <summary>Current emotional state (set by AI responses).</summary>
        public string CurrentMood { get; private set; } = "curious";

        /// <summary>True if Dobby is currently showing dialogue.</summary>
        public bool IsSpeaking { get; private set; }

        public static DobbyController Instance { get; private set; }

        private float dialogueTimer;

        private void Awake()
        {
            if (Instance != null && Instance != this)
            {
                Destroy(gameObject);
                return;
            }
            Instance = this;
        }

        private void Start()
        {
            if (animator == null)
                animator = GetComponent<Animator>();

            // Listen for AI responses to show Dobby's dialogue
            var voiceProcessor = FindObjectOfType<VoiceCommandProcessor>();
            if (voiceProcessor != null)
                voiceProcessor.OnAIResponseReceived += OnAIResponse;

            HideDialogue();
        }

        private void Update()
        {
            // Auto-hide dialogue after timer
            if (IsSpeaking)
            {
                dialogueTimer -= Time.deltaTime;
                if (dialogueTimer <= 0)
                    HideDialogue();
            }

            // Billboard effect: dialogue faces camera
            if (billboardDialogue && dialogueText != null && Camera.main != null)
            {
                dialogueText.transform.rotation = Quaternion.LookRotation(
                    dialogueText.transform.position - Camera.main.transform.position);
            }
        }

        // ------------------------------------------------------------------
        // Public API
        // ------------------------------------------------------------------

        /// <summary>Show dialogue text above Dobby's head.</summary>
        public void ShowDialogue(string text)
        {
            if (dialogueText == null) return;

            dialogueText.text = text;
            dialogueText.gameObject.SetActive(true);
            dialogueTimer = dialogueDisplayTime;
            IsSpeaking = true;

            Log($"Dobby says: \"{text}\"");
        }

        /// <summary>Hide the dialogue text.</summary>
        public void HideDialogue()
        {
            if (dialogueText != null)
                dialogueText.gameObject.SetActive(false);
            IsSpeaking = false;
        }

        /// <summary>Set Dobby's emotional state (affects idle animations).</summary>
        public void SetMood(string mood)
        {
            CurrentMood = mood;
            Log($"Mood changed to: {mood}");

            if (animator == null) return;

            // Set animator parameter for mood-based idle variations
            animator.SetBool("IsScared", mood == "scared");
            animator.SetBool("IsHappy", mood == "joyful" || mood == "excited");
        }

        /// <summary>Play a specific animation trigger.</summary>
        public void PlayAnimation(string triggerName)
        {
            if (animator != null)
                animator.SetTrigger(triggerName);
            Log($"Animation: {triggerName}");
        }

        /// <summary>Make Dobby look at a specific position (for cutscenes).</summary>
        public void LookAt(Vector3 worldPosition)
        {
            Vector3 direction = worldPosition - transform.position;
            direction.y = 0; // Keep upright
            if (direction.sqrMagnitude > 0.001f)
                transform.rotation = Quaternion.LookRotation(direction);
        }

        // ------------------------------------------------------------------
        // Event Handlers
        // ------------------------------------------------------------------

        private void OnAIResponse(AICommandResponse response)
        {
            // Show Dobby's dialogue from AI
            if (!string.IsNullOrEmpty(response.dobby_dialogue))
                ShowDialogue(response.dobby_dialogue);

            // Update mood
            if (!string.IsNullOrEmpty(response.mood))
                SetMood(response.mood);
        }

        private void OnDestroy()
        {
            var voiceProcessor = FindObjectOfType<VoiceCommandProcessor>();
            if (voiceProcessor != null)
                voiceProcessor.OnAIResponseReceived -= OnAIResponse;
        }

        private void Log(string message)
        {
            if (logEvents)
                Debug.Log($"[Dobby] {message}");
        }
    }
}
