using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using UnityEngine;

namespace EchoRealm.AI
{
    /// <summary>
    /// Manages the narrative context of the EchoRealm experience.
    /// Tracks user actions, scene changes, and cooperation events to build
    /// a session summary that the AI uses for adaptive storytelling.
    ///
    /// Also handles:
    /// - Generating AI hints when users are stuck
    /// - Requesting the final Oracle monologue
    /// - Tracking narrative "mood" across the session
    /// </summary>
    public class NarrativeManager : MonoBehaviour
    {
        [Header("References")]
        [SerializeField] private AIManager aiManager;
        [SerializeField] private CommandExecutor commandExecutor;

        [Header("Hint System")]
        [Tooltip("Seconds of inactivity before generating a hint.")]
        [SerializeField] private float hintDelaySeconds = 30f;

        [Header("Debug")]
        [SerializeField] private bool logEvents = true;

        /// <summary>All voice commands given during this session.</summary>
        public List<string> VoiceCommandLog { get; private set; } = new List<string>();

        /// <summary>All AI commands executed during this session.</summary>
        public List<string> ExecutedCommandLog { get; private set; } = new List<string>();

        /// <summary>Current narrative mood (set by AI responses).</summary>
        public string CurrentMood { get; private set; } = "mysterious";

        /// <summary>Current act number (1-4).</summary>
        public int CurrentAct { get; private set; } = 1;

        /// <summary>Session start time.</summary>
        public float SessionStartTime { get; private set; }

        /// <summary>Number of cooperation events detected.</summary>
        public int CooperationCount { get; private set; }

        /// <summary>Fired when a hint is generated by the AI.</summary>
        public event Action<string> OnHintGenerated;

        /// <summary>Fired when the final Oracle monologue is generated.</summary>
        public event Action<string> OnFinalMonologueGenerated;

        public static NarrativeManager Instance { get; private set; }

        private float lastInteractionTime;
        private bool hintRequested;

        private void Awake()
        {
            if (Instance != null && Instance != this)
            {
                Destroy(gameObject);
                return;
            }
            Instance = this;
        }

        private void Start()
        {
            SessionStartTime = Time.time;
            lastInteractionTime = Time.time;

            if (aiManager == null)
                aiManager = FindObjectOfType<AIManager>();
            if (commandExecutor == null)
                commandExecutor = FindObjectOfType<CommandExecutor>();

            // Subscribe to events
            var voiceProcessor = FindObjectOfType<VoiceCommandProcessor>();
            if (voiceProcessor != null)
            {
                voiceProcessor.OnSpeechRecognized += OnVoiceCommand;
                voiceProcessor.OnAIResponseReceived += OnAIResponse;
            }

            if (commandExecutor != null)
                commandExecutor.OnCommandExecuted += OnCommandExecuted;
        }

        private void Update()
        {
            // Check for inactivity (hint system)
            if (CurrentAct == 3 && !hintRequested &&
                Time.time - lastInteractionTime > hintDelaySeconds)
            {
                hintRequested = true;
                GenerateHint();
            }
        }

        // ------------------------------------------------------------------
        // Public API
        // ------------------------------------------------------------------

        /// <summary>Advance to the next act.</summary>
        public void AdvanceAct()
        {
            CurrentAct = Mathf.Min(CurrentAct + 1, 4);
            Log($"Advanced to Act {CurrentAct}");
        }

        /// <summary>Record a cooperation event between players.</summary>
        public void RecordCooperation(string description)
        {
            CooperationCount++;
            Log($"Cooperation #{CooperationCount}: {description}");
        }

        /// <summary>
        /// Build a summary of the entire session for the final Oracle monologue.
        /// </summary>
        public string BuildSessionSummary()
        {
            float durationMinutes = (Time.time - SessionStartTime) / 60f;

            var summary = $"Session duration: {durationMinutes:F1} minutes. " +
                          $"Total voice commands: {VoiceCommandLog.Count}. " +
                          $"Total effects activated: {ExecutedCommandLog.Count}. " +
                          $"Cooperation events: {CooperationCount}. " +
                          $"Current mood: {CurrentMood}. ";

            if (VoiceCommandLog.Count > 0)
            {
                // Include last 5 voice commands for context
                int start = Mathf.Max(0, VoiceCommandLog.Count - 5);
                var recentCommands = VoiceCommandLog.GetRange(start, VoiceCommandLog.Count - start);
                summary += $"Recent voice commands: [{string.Join("; ", recentCommands)}]. ";
            }

            if (ExecutedCommandLog.Count > 0)
            {
                // Include unique effects used
                var uniqueEffects = new HashSet<string>(ExecutedCommandLog);
                summary += $"Unique effects used: [{string.Join(", ", uniqueEffects)}]. ";
            }

            return summary;
        }

        /// <summary>
        /// Request the AI to generate the final Oracle monologue (Act 4).
        /// </summary>
        public async Task<string> GenerateFinalMonologue()
        {
            if (aiManager == null || !aiManager.IsReachable)
            {
                Log("No AI backend available for final monologue.", isWarning: true);
                return GetFallbackMonologue();
            }

            string sessionSummary = BuildSessionSummary();

            string prompt =
                "You are the Oracle of EchoRealm — a mysterious, wise entity made of light and particles. " +
                "The interactive mixed reality film is ending. Two users (wearing HoloLens 2 headsets) " +
                "have been transforming the world with their voice and cooperating to solve challenges. " +
                $"Here is what happened in this session: {sessionSummary} " +
                "Generate a final monologue (3-5 sentences) that: " +
                "1. Reflects on what the users did and chose during the experience. " +
                "2. Has a tone matching the session mood (mysterious, joyful, melancholic, or excited). " +
                "3. Ends with a poetic farewell as the astronaut steps through the portal. " +
                "Return ONLY the monologue text, no JSON, no quotes.";

            Log($"Generating final Oracle monologue via {aiManager.ActiveBackendName}...");
            string monologue = await aiManager.SendPromptAsync(prompt);

            if (string.IsNullOrEmpty(monologue))
            {
                monologue = GetFallbackMonologue();
            }

            // Clean up: Ollama might still return JSON even with instructions not to
            monologue = CleanMonologue(monologue);

            Log($"Final monologue: {monologue}");
            OnFinalMonologueGenerated?.Invoke(monologue);

            return monologue;
        }

        // ------------------------------------------------------------------
        // Hint System
        // ------------------------------------------------------------------

        private async void GenerateHint()
        {
            if (aiManager == null || !aiManager.IsReachable || aiManager.IsBusy)
                return;

            string sceneState = commandExecutor != null ? commandExecutor.GetSceneStateDescription() : "unknown";

            string prompt =
                "You are the Oracle guiding users in EchoRealm. They are stuck on a cooperative challenge " +
                "(Act 3 — they need to work together to overcome an obstacle). " +
                $"Current scene: {sceneState}. " +
                $"They have given {VoiceCommandLog.Count} voice commands so far. " +
                "Give a short, mysterious hint (1-2 sentences) to help them cooperate. " +
                "Be poetic and in character as the Oracle. " +
                "Return ONLY the hint text.";

            Log($"Generating hint via {aiManager.ActiveBackendName}...");
            string hint = await aiManager.SendPromptAsync(prompt);

            if (!string.IsNullOrEmpty(hint))
            {
                hint = CleanMonologue(hint);
                Log($"Hint: {hint}");
                OnHintGenerated?.Invoke(hint);
            }
        }

        // ------------------------------------------------------------------
        // Event Handlers
        // ------------------------------------------------------------------

        private void OnVoiceCommand(string text)
        {
            VoiceCommandLog.Add(text);
            lastInteractionTime = Time.time;
            hintRequested = false; // Reset hint timer on new interaction
        }

        private void OnAIResponse(AICommandResponse response)
        {
            if (!string.IsNullOrEmpty(response.mood))
                CurrentMood = response.mood;
        }

        private void OnCommandExecuted(string command)
        {
            ExecutedCommandLog.Add(command);
        }

        // ------------------------------------------------------------------
        // Helpers
        // ------------------------------------------------------------------

        private string GetFallbackMonologue()
        {
            return "Your voices have shaped this realm in ways I could not foresee. " +
                   "The echoes of your choices will linger here long after you depart. " +
                   "Step through the portal now — carry what you have learned back to your world. " +
                   "EchoRealm will remember you.";
        }

        private string CleanMonologue(string text)
        {
            if (string.IsNullOrEmpty(text)) return text;

            // Remove surrounding quotes if present
            text = text.Trim().Trim('"').Trim('\'');

            // Try to extract from JSON if Ollama wrapped it anyway
            if (text.StartsWith("{"))
            {
                try
                {
                    // Simple extraction: find first string value
                    int colonIdx = text.IndexOf(':');
                    if (colonIdx > 0)
                    {
                        string afterColon = text.Substring(colonIdx + 1).Trim().Trim('"');
                        int endQuote = afterColon.IndexOf('"');
                        if (endQuote > 0)
                            return afterColon.Substring(0, endQuote);
                    }
                }
                catch { /* fall through to return as-is */ }
            }

            return text;
        }

        private void Log(string message, bool isWarning = false)
        {
            if (!logEvents) return;
            if (isWarning)
                Debug.LogWarning($"[Narrative] {message}");
            else
                Debug.Log($"[Narrative] {message}");
        }
    }
}
